import Link from "next/link";
import { HelpCircle, Lock, Shield, Trophy, Users, WalletCards } from "lucide-react";
import { PublicNav } from "@/components/layout/PublicNav";

const categories = [["Scoring & Rules", Trophy], ["Tokens & Rewards", WalletCards], ["Payouts", Shield], ["Affiliates", Users], ["Sponsors", Shield], ["Account & Security", Lock]] as const;
const faqs = [
  ["How do scoring points work?", "Points are awarded for correct winner, method, round, and key fight stats. Each contest stores its scoring rules so results stay auditable."],
  ["What are tokens used for?", "Tokens are used to enter eligible contests. Promotional credits and withdrawable rewards are tracked separately for transparency."],
  ["How do payouts work?", "Withdrawable rewards can be requested from the wallet and reviewed before settlement."],
  ["When do predictions lock?", "Predictions lock at the scheduled lock time. After lock, picks cannot be edited."],
  ["Can I edit picks after entering?", "Yes, until the contest lock time. After lock, all picks become immutable."],
  ["What happens if a fight is canceled?", "Contest entries are refunded according to the contest rules snapshot."],
];
export default function FaqPage(){return <div className="page-shell"><PublicNav/><section className="bg-hero-fade border-b border-white/10"><div className="container-wide py-16"><h1 className="text-6xl font-black uppercase">FAQ & <span className="text-madness-red">Help Center</span></h1><p className="mt-4 max-w-2xl text-lg text-white/70">Find answers about scoring, contests, tokens, payouts, affiliates, sponsors, and fair play.</p><div className="mt-6 max-w-xl rounded-xl border border-madness-red/60 bg-black/60 p-4 text-white/55">🔎 Search for answers...</div><div className="mt-8 grid gap-4 md:grid-cols-3 xl:grid-cols-6">{categories.map(([name,Icon])=><div key={name} className="glass-card p-4"><Icon className="mb-3 h-8 w-8 text-madness-red"/><b>{name}</b><p className="text-sm text-white/50">Learn more</p></div>)}</div></div></section><main className="container-wide grid gap-6 py-8 lg:grid-cols-[1fr_420px]"><section><h2 className="section-title mb-4">Frequently Asked Questions</h2>{faqs.map(([q,a],i)=><details key={q} className="panel mb-3 p-5" open={i<4}><summary className="cursor-pointer text-lg font-black text-madness-red">{q}</summary><p className="mt-3 text-white/65">{a}</p></details>)}</section><aside className="space-y-6"><div className="panel p-6"><HelpCircle className="h-10 w-10 text-madness-red"/><h3 className="mt-3 text-xl font-black uppercase">Contact Support</h3><p className="mt-2 text-white/60">Live chat, email support, and fast response for contest issues.</p><button className="btn-primary mt-5 w-full">Open Support Ticket</button></div><div className="panel p-6"><h3 className="text-xl font-black uppercase">Built on Trust</h3>{["Transparent Scoring","Secure Payouts","Anti-Cheat Monitoring"].map(x=><p key={x} className="mt-3 text-white/70">✓ {x}</p>)}<Link href="/how-to-play" className="mt-4 inline-block text-madness-red">Read Fair Play Policy →</Link></div></aside></main></div>}
