import React, { useEffect, useState } from 'react'; import Head from 'next/head'; import { fullCardRequest } from '@/Utils/fullCardApi';
export default function AdminFullCards() { const [cards, setCards] = useState([]); const [affiliates, setAffiliates] = useState([]); const [selected, setSelected] = useState(''); const [invite, setInvite] = useState(''); const [signupLink, setSignupLink] = useState(''); const [recipientEmail, setRecipientEmail] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [c, a] = await Promise.all([fullCardRequest('/api/admin/full-cards', { kind: 'admin' }), fullCardRequest('/affiliates', { kind: 'admin' })]); setCards(c.cards || []); setAffiliates(Array.isArray(a) ? a : a.affiliates || []); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  const approve = async () => { if (!selected || busy) return; setBusy(true); setMessage(''); try { await fullCardRequest(`/api/admin/full-card-promoters/${selected}`, { method: 'PATCH', kind: 'admin', body: { enabled: true, role: 'PROMOTER' } }); setInvite(''); setMessage('Promoter approved. Full Card tools are available in their affiliate account now.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const invitePromoter = async () => { if (!selected || busy) return; setBusy(true); setMessage(''); try { const data = await fullCardRequest('/api/admin/full-card-promoter-invites', { method: 'POST', kind: 'admin', body: { affiliateId: selected, expiresInDays: 14 } }); setInvite(data.url); setMessage('Promoter access is active now. Share this private link with the selected affiliate.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const createPreapprovedSignup = async () => { if (busy) return; setBusy(true); setMessage(''); try { const data = await fullCardRequest('/api/admin/affiliate-invites', { method: 'POST', kind: 'admin', body: { expiresInDays: 14, promoterAccess: true, recipientEmail: recipientEmail.trim() } }); setSignupLink(data.url); setMessage('Pre-approved promoter signup link created. The recipient gets affiliate and Full Card access when they register.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const action = async (id, body) => { try { await fullCardRequest(`/api/admin/full-cards/${id}`, { method: 'PATCH', kind: 'admin', body }); await load(); } catch (e) { setMessage(e.message); } };
  const copyPromotionalLink = async (url) => { try { await navigator.clipboard.writeText(url); setMessage('Promotional link copied.'); } catch (_error) { setMessage('Select the link and copy it manually.'); } };
  return <main className="admin-full-card-page"><Head><title>Full Card Control Center</title></Head><header><p>OWNER OPERATIONS</p><h1>Full Card Control Center</h1><span>Approve promoters, govern events, locks, and public availability.</span></header>{message && <div className="full-card-notice">{message}</div>}
    <section className="admin-promoter-access"><h2>Promoter access</h2><p>Approve an affiliate instantly, or create a private invitation that also grants access right away.</p><select aria-label="Select affiliate for promoter access" value={selected} onChange={(e) => { setSelected(e.target.value); setInvite(''); }}><option value="">Select affiliate…</option>{affiliates.map((a) => <option value={a._id} key={a._id}>{a.playerName || `${a.firstName || ''} ${a.lastName || ''}`} · {a.email}</option>)}</select><button type="button" disabled={!selected || busy} onClick={approve}>{busy ? 'Working…' : 'Approve promoter now'}</button><button type="button" disabled={!selected || busy} onClick={invitePromoter}>Create private invitation link</button>{invite && <div><input aria-label="Private promoter invitation link" readOnly value={invite} onFocus={(event) => event.target.select()} /><button type="button" onClick={() => navigator.clipboard.writeText(invite)}>Copy</button></div>}</section>
    <section className="admin-promoter-access"><h2>Pre-approved promoter signup</h2><p>Send a one-time link to a new promoter. They create an affiliate account and can build Full Cards immediately after signing in. The link expires in 14 days.</p><label>Recipient email (optional; locks the link to this address)<input type="email" value={recipientEmail} onChange={(event) => setRecipientEmail(event.target.value)} placeholder="promoter@example.com" /></label><button type="button" disabled={busy} onClick={createPreapprovedSignup}>{busy ? 'Creating…' : 'Create pre-approved promoter link'}</button>{signupLink && <div><input aria-label="Pre-approved promoter signup link" readOnly value={signupLink} onFocus={(event) => event.target.select()} /><button type="button" onClick={() => navigator.clipboard.writeText(signupLink)}>Copy link</button></div>}</section>
    <section className="admin-full-card-table"><header><h2>Promoter events</h2><span>{cards.length} cards</span></header>{cards.map((card) => <article key={card.id}><div><strong>{card.eventName}</strong><span>{card.promoter?.name} · {card.bouts?.length || 0} fights · {card.status}</span>{['UPCOMING', 'LIVE', 'COMPLETED'].includes(card.status) && card.shareUrl && <label>Promoter's full-card link<input aria-label={`${card.eventName} promoter link`} readOnly value={card.shareUrl} onFocus={(event) => event.target.select()} style={{ width: '100%' }} /><button type="button" onClick={() => copyPromotionalLink(card.shareUrl)}>Copy promotional link</button> <a href={card.shareUrl} target="_blank" rel="noopener noreferrer">Open card</a></label>}</div><div><button onClick={() => action(card.id, { locked: !card.lockedAt })}>{card.lockedAt ? 'Unlock' : 'Lock'}</button><button onClick={() => action(card.id, { status: 'UNPUBLISHED', reason: 'Unpublished by owner' })}>Unpublish</button><button onClick={() => action(card.id, { status: 'CANCELLED', reason: 'Cancelled by owner' })}>Cancel</button></div></article>)}</section>
  </main>; }
