import React, { useEffect, useState } from 'react'; import Head from 'next/head'; import { fullCardRequest } from '@/Utils/fullCardApi';
export default function AdminFullCards() { const [cards, setCards] = useState([]); const [affiliates, setAffiliates] = useState([]); const [selected, setSelected] = useState(''); const [invite, setInvite] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const [c, a] = await Promise.all([fullCardRequest('/api/admin/full-cards', { kind: 'admin' }), fullCardRequest('/affiliates', { kind: 'admin' })]); setCards(c.cards || []); setAffiliates(Array.isArray(a) ? a : a.affiliates || []); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  const grant = async () => { try { await fullCardRequest(`/api/admin/full-card-promoters/${selected}`, { method: 'PATCH', kind: 'admin', body: { enabled: true, role: 'PROMOTER' } }); const data = await fullCardRequest('/api/admin/full-card-promoter-invites', { method: 'POST', kind: 'admin', body: { affiliateId: selected, expiresInDays: 14 } }); setInvite(data.url); setMessage('Promoter permission enabled and private invitation created.'); } catch (e) { setMessage(e.message); } };
  const action = async (id, body) => { try { await fullCardRequest(`/api/admin/full-cards/${id}`, { method: 'PATCH', kind: 'admin', body }); await load(); } catch (e) { setMessage(e.message); } };
  return <main className="admin-full-card-page"><Head><title>Full Card Control Center</title></Head><header><p>OWNER OPERATIONS</p><h1>Full Card Control Center</h1><span>Approve promoters, govern events, locks, and public availability.</span></header>{message && <div className="full-card-notice">{message}</div>}
    <section className="admin-promoter-access"><h2>Promoter access</h2><select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Select affiliate…</option>{affiliates.map((a) => <option value={a._id} key={a._id}>{a.playerName || `${a.firstName || ''} ${a.lastName || ''}`} · {a.email}</option>)}</select><button disabled={!selected} onClick={grant}>Enable & create invitation</button>{invite && <div><input readOnly value={invite} /><button onClick={() => navigator.clipboard.writeText(invite)}>Copy</button></div>}</section>
    <section className="admin-full-card-table"><header><h2>Promoter events</h2><span>{cards.length} cards</span></header>{cards.map((card) => <article key={card.id}><div><strong>{card.eventName}</strong><span>{card.promoter?.name} · {card.bouts?.length || 0} fights · {card.status}</span></div><div><button onClick={() => action(card.id, { locked: !card.lockedAt })}>{card.lockedAt ? 'Unlock' : 'Lock'}</button><button onClick={() => action(card.id, { status: 'UNPUBLISHED', reason: 'Unpublished by owner' })}>Unpublish</button><button onClick={() => action(card.id, { status: 'CANCELLED', reason: 'Cancelled by owner' })}>Cancel</button></div></article>)}</section>
  </main>; }

